<?php

namespace AppBundle\Repository;

/**
 * IMEIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IMEIRepository extends \Doctrine\ORM\EntityRepository
{
}
