<?php

namespace AppBundle\Repository;

/**
 * WarehouseIMEIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseIMEIRepository extends \Doctrine\ORM\EntityRepository
{
}
