<?php

namespace AppBundle\Repository;

/**
 * WarehouseMasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseMasterRepository extends \Doctrine\ORM\EntityRepository
{
}
